//tabInsetUI Actions
export const SET_INSET_TAB_UI = "SET_INSET_TAB_UI";

//modalUI Actions
export const MODAL_USER_INFO_INPUT = "MODAL_USER_INFO_INPUT";
export const MODAL_CITY_SEARCH = "MODAL_CITY_SEARCH";
export const MODAL_INTEREST_SELECTOR = "MODAL_INTEREST_SELECTOR";

//registrationUI Actions
export const SET_REGISTRATION_UI = "SET_REGISTRATION_UI";
export const SET_USER_INFO_INPUT_FINISHED = "SET_USER_INFO_INPUT_FINISHED";

//user Actions
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_FIRST_NAME = "SET_USER_FIRST_NAME";
export const SET_USER_LAST_NAME = "SET_USER_LAST_NAME";
export const SET_USER_AGE = "SET_USER_AGE";
export const SET_USER_CITY = "SET_USER_CITY";
export const ADD_TO_USER_PASSIONS_LIST = "ADD_TO_USER_PASSIONS_LIST";
export const REMOVE_FROM_USER_PASSIONS_LIST = "REMOVE_FROM_USER_PASSIONS_LIST";

export const GET_USER_DATA = "GET_USER_DATA";

export const USER_SIGNUP = "USER_SIGNUP";

export const POST_NEW_USER_SIGNUP = "POST_NEW_USER_SIGNUP";
export const NEW_USER_SIGNUP_SUCEEDED = "NEW_USER_SIGNUP_SUCEEDED";
export const NEW_USER_SIGNUP_FAILED = "NEW_USER_SIGNUP_FAILED";
